questions = [
    "If you had god-like powers for one day, what would you do with them?",
    "If you had the chance to talk to anyone, alive or dead, who would it be and what would you talk about?",
    "What's worse and why: having expectations that are too high or having no expectations at all?",
    "What is the most important invention of our time?",
    "If you were stranded on a desert island and could only bring 3 things, what would you choose to bring and why?",
    "If you had a time machine that allowed you to visit any time period in the past, which period would you visit?",
    "If you had a time machine that could travel backward or forward in time, would you rather go to the past or future? Why?",
    "What do you think the world will be like in 50 years? 100 years? 1000 years?",
    "If you could only eat 4 different foods for the remainder of your life, what foods would you choose?",
    "What would your ideal profession be?",
    "What is the most embarrassing thing you have ever done?",
    "What is your deepest, most primal fear?",
    "When have you felt your loneliest?",
    "Which, if any, childhood dreams never came true for you?",
    "Are you happy with the way your life is going? If there were one thing you could change about your life, what would it be?",
    "Which topics, if any, are too serious to ever joke about?",
    "What is your biggest regret?",
    "What is your biggest triumph?",
    "What one thing would you like to be remembered for?",
    "If there were one important memory you had to forget, what memory would you choose?",
    "What was the last thing you regretted purchasing?",
    "What, if anything, have you regretted never taking the time to learn?",
    "If you could re-live one day of your life, what day would it be?",
    "What do you do at your job?",
    "Where did you grow up?",
    "What was your family like growing up? What is your family like now?",
    "What is your favorite snack food?",
    "What was your favorite / least favorite year of school and why?",
    "What is the most embarrassing song or CD in your collection?",
    "What is the most embarrassing movie/DVD/Blu-ray in your collection?",
    "If you could travel anywhere in the world, where would it be and why?",
    "What are your favorite television shows?",
    "What is your favorite movie of all time?",
    "Who was your most memorable childhood friend?",
    "Who, if anyone, was your biggest childhood hero?",
    "What is your earliest memory?",
    "What is your favorite book or story?",
    "What are your hobbies?",
    "What is the silliest or strangest thing you've ever done to impress someone you had romantic feelings for?",
    "If your life were turned into a book or movie, what would the title be?",
    "What was your favorite pet and why?",
    "If you saw someone shoplifting, what would you do?",
    "If your dog and a stranger were trapped in a burning building and you could only save one, which would it be? If your dog and your worst enemy were trapped in a burning building and you could only save one, which would it be?",
    "If you hit a car in a parking lot and no one saw, what would you do?",
    "If someone gave you too much change at a store, would you keep it or give it back?",
    "If you found a large amount of money, would you report it?",
    "If you saw a child or a pet locked in a car on a hot day, what would you do?",
    "What would you do if you saw a friend's significant other cheating on your friend with another man or woman?"
]