from collections import deque

usedTopics = deque()

questions = [
    "If you had god-like powers for one day, what would you do with them?",
    "If you had the chance to talk to anyone, alive or dead, who would it be and what would you talk about?",
    "What's worse and why: having expectations that are too high or having no expectations at all?",
    "What is the most important invention of our time?",
    "If you were stranded on a desert island and could only bring 3 things, what would you choose to bring and why?",
    "If you had a time machine that allowed you to visit any time period in the past, which period would you visit?",
    "If you had a time machine that could travel backward or forward in time, would you rather go to the past or future? Why?",
    "What do you think the world will be like in 50 years? 100 years? 1000 years?",
    "If you could only eat 4 different foods for the remainder of your life, what foods would you choose?",
    "What would your ideal profession be?",
    "What is the most embarrassing thing you have ever done?",
    "What is your deepest, most primal fear?",
    "When have you felt your loneliest?",
    "Which, if any, childhood dreams never came true for you?",
    "Are you happy with the way your life is going? If there were one thing you could change about your life, what would it be?",
    "Which topics, if any, are too serious to ever joke about?",
    "What is your biggest regret?",
    "What is your biggest triumph?",
    "What one thing would you like to be remembered for?",
    "If there were one important memory you had to forget, what memory would you choose?",
    "What was the last thing you regretted purchasing?",
    "What, if anything, have you regretted never taking the time to learn?",
    "If you could re-live one day of your life, what day would it be?",
    "What do you do at your job?",
    "Where did you grow up?",
    "What was your family like growing up? What is your family like now?",
    "What is your favorite snack food?",
    "What was your favorite / least favorite year of school and why?",
    "What is the most embarrassing song or CD in your collection?",
    "What is the most embarrassing movie/DVD/Blu-ray in your collection?",
    "If you could travel anywhere in the world, where would it be and why?",
    "What are your favorite television shows?",
    "What is your favorite movie of all time?",
    "Who was your most memorable childhood friend?",
    "Who, if anyone, was your biggest childhood hero?",
    "What is your earliest memory?",
    "What is your favorite book or story?",
    "What are your hobbies?",
    "What is the silliest or strangest thing you've ever done to impress someone you had romantic feelings for?",
    "If your life were turned into a book or movie, what would the title be?",
    "What was your favorite pet and why?",
    "If you saw someone shoplifting, what would you do?",
    "If your dog and a stranger were trapped in a burning building and you could only save one, which would it be? If your dog and your worst enemy were trapped in a burning building and you could only save one, which would it be?",
    "If you hit a car in a parking lot and no one saw, what would you do?",
    "If someone gave you too much change at a store, would you keep it or give it back?",
    "If you found a large amount of money, would you report it?",
    "If you saw a child or a pet locked in a car on a hot day, what would you do?",
    "What would you do if you saw a friend's significant other cheating on your friend with another man or woman?",
    "What was the last funny video you saw?",
    "What do you do to get rid of stress?",
    "What is something you are obsessed with?",
    "What three words best describe you?",
    "What would be your perfect weekend?",
    "What’s your favorite number? Why?",
    "What are you going to do this weekend?",
    "What’s the most useful thing you own?",
    "What’s your favorite way to waste time?",
    "Do you have any pets? What are their names?",
    "Where did you go last weekend? / What did you do last weekend?",
    "What is something popular now that annoys you?",
    "What did you do on your last vacation?",
    "When was the last time you worked incredibly hard?",
    "Are you very active, or do you prefer to just relax in your free time?",
    "What do you do when you hang out with your friends?",
    "Who is your oldest friend? Where did you meet them?",
    "What’s the best / worst thing about your work/school?",
    "If you had intro music, what song would it be? Why?",
    "What were you really into when you were a kid?",
    "If you could have any animal as a pet, what animal would you choose?",
    "Have you ever saved an animal’s life? How about a person’s life?",
    "If you opened a business, what kind of business would it be?",
    "Who is your favorite entertainer (comedian, musician, actor, etc.)?",
    "Are you a very organized person?",
    "Have you ever given a presentation in front of a large group of people? How did it go?",
    "What is the strangest dream you have ever had?",
    "What is a controversial opinion you have?",
    "Who in your life brings you the most joy?",
    "Who had the biggest impact on the person you have become?",
    "What is the most annoying habit someone can have?",
    "Where is the most beautiful place you have been?",
    "Where do you spend most of your free time/day?",
    "How often do you stay up past 3 a.m. (all nighter)?",
    "What’s your favorite season? Why?",
    "Which is more important, having a great car or a great house? Why?",
    "What animal or insect do you wish humans could eradicate?",
    "Where is the most beautiful place near where you live?",
    "What do you bring with you everywhere you go?",
    "How much time do you spend on the internet? What do you usually do?",
    "What is the most disgusting habit some people have?",
    "Where and when was the most amazing sunset you have ever seen?",
    "Where is the worst place you have been stuck for a long time?",
    "If you had to change your name, what would your new name be?",
    "What is something that really annoys you but doesn’t bother most people?",
    "What word or saying from the past do you think should come back?",
    "What is your guilty pleasure?",
    "Was there ever an event in your life that defied explanation?",
    "If you could learn the answer to one question about your future, what would the question be?",
    "How often do you curse? And what’s your go-to string of curse words?",
    "What is the silliest fear you have?"
]